import React from 'react'
import {Inter} from 'next/font/google'
import Providers from '@/app/providers'
import NavBar from '@/app/components/NavBar'
import Footer from '@/app/components/Footer'
import 'devicon/devicon.min.css'
import './globals.css'
import './button.css'

export const revalidate = 60

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: 'Dev Blog',
  description: 'Generated by create next app',
}

interface Props {
    children: React.ReactNode
}

const RootLayout = ({children}: Props) => {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50 text-black dark:bg-slate-950 dark:text-white`}>
        <div className="flex h-screen flex-col">
          <Providers>
            <NavBar/>
            <div className="grow">
              <div className="py-24 sm:py-32">
                <div className="container mx-auto">
                  {children}
                </div>
              </div>
            </div>
            <Footer/>
          </Providers>
        </div>
      </body>
    </html>
  )
}

export default RootLayout
